# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('num_shs', models.IntegerField(verbose_name='Number of Shares Bought')),
                ('date', models.DateTimeField(verbose_name='Date of the Shares Bought')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('num_shs', models.IntegerField(verbose_name='Number of Shares Sold')),
                ('date', models.DateTimeField(verbose_name='Date of Shares Sold')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=6)),
                ('pool', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='stock_performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_stamp', models.DateTimeField()),
                ('shs_stamp', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=6)),
                ('transtype', models.CharField(choices=[('S', 'Sold'), ('B', 'Bought')], max_length=1)),
                ('date', models.DateTimeField()),
                ('num_shs', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='sell',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo.Stock'),
        ),
        migrations.AddField(
            model_name='buy',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo.Stock'),
        ),
    ]
