# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='reason',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sell',
            name='reason',
            field=models.CharField(max_length=200),
        ),
    ]
